version: 2
updates:
  - package-ecosystem: npm
    directory: '/projects/website'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
    ignore:
      - dependency-name: 'theme-ui/*'
  - package-ecosystem: npm
    directory: '/projects/next'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
