[tools]
  pnpm = "10.14"
  node = "24"
  sops = "3.9.3"
  age = "1.2.1"
  "ubi:aquasecurity/trivy" = "0.63.0"
  "clickhouse" = "25.5.1"
  "npm:prettier" = "3.4.2"
  "elixir" = "1.18.4"
  "flyctl" = "0.3.172"
  "erlang" = "27.3.2"
  "asdf:aeons/asdf-minio" = "latest"
  "npm:appium" = "3.0.1"

[env]
  TUIST_HOSTED = 1
  ERL_AFLAGS = "-kernel shell_history enabled -kernel shell_history_file_bytes 1024000"
