version: 1
update_configs:
  - package_manager: 'ruby:bundler'
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - 'tuist/core'
    default_labels:
      - 'dependencies'
  - package_manager: 'javascript'
    directory: '/website'
    update_schedule: 'weekly'
    default_reviewers:
      - 'tuist/core'
    default_labels:
      - 'dependencies'
