# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idname
name: Checks

# This workflow only runs when there are changes to the Swift code.
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - tools/fixturegen/**
      - tools/tuistbench/**

env:
  RUBY_VERSION: '2.7.2'

jobs:
  swiftformat:
    name: SwiftFormat with Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['12', '12.4']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Bundler 2.1.4
        run: gem install bundler --version 2.1.4
      - name: Install Bundler dependencies
        run: bundle install
      - name: Run swiftformat
        run: bundle exec rake swift_format
  swiftlint:
    name: Swiftlint with Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['12', '12.4']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Bundler 2.1.4
        run: gem install bundler --version 2.1.4
      - name: Install Bundler dependencies
        run: bundle install
      - name: Run swiftlint
        run: bundle exec rake swift_lint
