name: Fixture Generator

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - tools/fixturegen/**
      - Package.swift
      - Package.resolved
      - Sources/**

jobs:
  test:
    name: Test fixturegen with Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['12.0', '12.4']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Package
        working-directory: ./tools/fixturegen
        run: swift build
      - name: Generate Fixture
        working-directory: ./tools/fixturegen
        run: swift run fixturegen --projects 1 --targets 1 --sources 1
      - name: Build Tuist
        run: swift build
      - name: Generate Fixture Project
        run: swift run tuist generate --path ./tools/fixturegen/Fixture
