name: Galaxy

on:
  push:
    paths:
      - galaxy/**/*
      - .github/workflows/galaxy.yml
env:
  RAILS_ENV: test
  BUNDLER_VERSION: 2.0.2

jobs:
  style_lint:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install dependencies
        working-directory: ./galaxy
        run: |
          gem install bundler
          bundle install --jobs=4 --retry=3
      - name: Rubocop
        working-directory: ./galaxy
        run: |
          bundle exec rubocop
      - name: Brakeman
        working-directory: ./galaxy
        run: |
          bundle exec brakeman

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: ''
      redis:
        image: redis:4.0.6
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Install dependencies
        working-directory: ./galaxy
        run: |
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          gem install bundler
          bundle install --jobs=4 --retry=3
          yarn install
      - name: Set up database
        working-directory: ./galaxy
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run tests
        working-directory: ./galaxy
        run: |
          bundle exec rails test
