name: Handbook

on:
  push:
    branches:
      - main
    paths:
      - handbook/**
      - .github/workflows/handbook.yml
      - pnpm-lock.yaml
      - handbook/package.json
  pull_request:
    paths:
      - handbook/**
      - .github/workflows/handbook.yml
      - pnpm-lock.yaml
      - handbook/package.json
  merge_group:

concurrency:
  group: handbook-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  handbook-build:
    name: Build
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise run handbook:build
