name: Handbook

on:
  push:
    branches:
      - main
    paths:
      - handbook/**
      - .github/workflows/handbook.yml
      - pnpm-lock.yaml
      - handbook/package.json
  pull_request:
    paths:
      - handbook/**
      - .github/workflows/handbook.yml
      - pnpm-lock.yaml
      - handbook/package.json
  merge_group:

concurrency:
  group: handbook-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PNPM_HOME: ~/.pnpm

defaults:
  run:
    working-directory: handbook

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('./pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Build handbook
        run: mise run build
      - name: Deploy to Cloudflare Pages
        if: github.ref == 'refs/heads/main'
        env:
          MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: mise run deploy
