name: Release dry-run

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - Tuist/Package.swift
      - Tuist/Package.resolved
      - Package.resolved
      - Gemfile*
      - Package.swift
      - Sources/**
      - Project.swift
      - projects/fourier/**
      - .github/workflows/release-dry-run.yml

env:
  RUBY_VERSION: '3.0.3'
  TUIST_STATS_OPT_OUT: true

jobs:
  bundle:
    name: Bundle
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Bundle
        run: |
          make workspace/release/bundle
