name: Tuist Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - tools/tuistbench/**

env:
  TUIST_STATS_OPT_OUT: true

jobs:
  test:
    name: Build tuistbench with Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['12.0', '12.4']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Package
        working-directory: ./tools/tuistbench
        run: swift build
